### model
model_name_or_path: /media/zhaogang/4T2-2-LLM/HuggingFace/models/qwen/qwen-2.5-7b
adapter_name_or_path: saves/qwen-2.5-7b/lora/sft
trust_remote_code: true

### method
finetuning_type: lora


### dataset
task: mmlu_test  # choices: [mmlu_test, ceval_validation, cmmlu_test]
template: fewshot
lang: en
n_shot: 5

### output
save_dir: saves/qwen-2.5-7b/lora/eval

### eval
batch_size: 2
